import { Request, Response } from "express";
import { Prisma } from "../../generated/prisma/client";
import { createPatient, getPatientDetails, getPatientSummary, listPatients, updatePatient } from "./admin-patients.service";
import { createPatientSchema, patientIdSchema, patientListQuerySchema, updatePatientSchema } from "./admin-patients.validation";

const databaseError = (error: unknown, response: Response) => { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") { response.status(409).json({ success: false, message: "A patient with this name and phone number already exists." }); return; } console.error("Unable to process patient request", error); response.status(500).json({ success: false, message: "Unable to process the patient request." }); };
export const getSummary = async (_request: Request, response: Response) => { try { response.status(200).json({ success: true, data: await getPatientSummary() }); } catch (error) { databaseError(error, response); } };
export const getPatients = async (request: Request, response: Response) => { const validation = patientListQuerySchema.safeParse(request.query); if (!validation.success) { response.status(400).json({ success: false, message: "Invalid patient filters.", errors: validation.error.flatten().fieldErrors }); return; } try { response.status(200).json({ success: true, data: await listPatients(validation.data) }); } catch (error) { databaseError(error, response); } };
export const getPatient = async (request: Request, response: Response) => { const id = patientIdSchema.safeParse(request.params.patientId); if (!id.success) { response.status(400).json({ success: false, message: "Enter a valid Patient ID." }); return; } try { const data = await getPatientDetails(id.data); if (!data) { response.status(404).json({ success: false, message: "Patient was not found." }); return; } response.status(200).json({ success: true, data }); } catch (error) { databaseError(error, response); } };
export const postPatient = async (request: Request, response: Response) => { const validation = createPatientSchema.safeParse(request.body); if (!validation.success) { response.status(400).json({ success: false, message: "Please correct the patient fields.", errors: validation.error.flatten().fieldErrors }); return; } try { response.status(201).json({ success: true, message: "Patient created successfully.", data: await createPatient(validation.data) }); } catch (error) { databaseError(error, response); } };
export const patchPatient = async (request: Request, response: Response) => { const id = patientIdSchema.safeParse(request.params.patientId); const validation = updatePatientSchema.safeParse(request.body); if (!id.success) { response.status(400).json({ success: false, message: "Enter a valid Patient ID." }); return; } if (!validation.success) { response.status(400).json({ success: false, message: "Please correct the patient fields.", errors: validation.error.flatten().fieldErrors }); return; } try { const data = await updatePatient(id.data, validation.data); if (!data) { response.status(404).json({ success: false, message: "Patient was not found." }); return; } response.status(200).json({ success: true, message: "Patient updated successfully.", data }); } catch (error) { databaseError(error, response); } };
