import { FormEvent, useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { AdminSidebar } from "../../../components/admin/AdminSidebar";
import { logoutAdmin } from "../admin-dashboard.service";
import { Doctor } from "../doctors/admin-doctors.types";
import { assignAppointment, changeAppointmentStatus, getAppointmentDetail, getAppointments, getAppointmentSummary, getAssignableDoctors } from "./admin-appointments.service";
import { Appointment, AppointmentDetail, AppointmentStatus, AppointmentSummary } from "./admin-appointments.types";
import "./AdminAppointments.css";

const tabs: Array<["ALL" | AppointmentStatus, keyof AppointmentSummary, string]> = [["ALL", "all", "All"], ["REQUESTED", "requested", "Pending"], ["ASSIGNED", "assigned", "Assigned"], ["COMPLETED", "completed", "Completed"], ["CANCELLED", "cancelled", "Cancelled"]];
const toDisplayDate = (value: string) => value.split("-").reverse().join("-");
const today = new Date().toLocaleDateString("en-CA");
const times = ["10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM"];

export const AdminAppointments = () => {
  const navigate = useNavigate(); const [active, setActive] = useState<"ALL" | AppointmentStatus>("ALL"); const [items, setItems] = useState<Appointment[]>([]); const [summary, setSummary] = useState<AppointmentSummary>({ all: 0, requested: 0, assigned: 0, completed: 0, cancelled: 0 }); const [doctors, setDoctors] = useState<Doctor[]>([]); const [selected, setSelected] = useState<AppointmentDetail | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [loggingOut, setLoggingOut] = useState(false); const [form, setForm] = useState({ doctorId: "", scheduledDate: "", scheduledTime: "", note: "" });
  const handleError = useCallback((reason: unknown) => { if (reason instanceof Error && reason.message === "SESSION_INVALID") navigate("/login", { replace: true }); else setError(reason instanceof Error ? reason.message : "Unable to load appointments."); }, [navigate]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [list, counts, doctorList] = await Promise.all([getAppointments(active === "ALL" ? undefined : active), getAppointmentSummary(), getAssignableDoctors()]); setItems(list); setSummary(counts); setDoctors(doctorList); if (selected) { const current = list.find((item) => item.referenceId === selected.appointment.referenceId); if (!current) setSelected(null); } } catch (reason) { handleError(reason); } finally { setLoading(false); } }, [active, handleError, selected]);
  useEffect(() => { void load(); }, [active]); // selected deliberately refreshed after mutations
  const choose = async (item: Appointment) => { setError(""); try { const detail = await getAppointmentDetail(item.referenceId); setSelected(detail); setForm({ doctorId: item.assignedDoctor?.doctorId ?? "", scheduledDate: (item.scheduledDate ?? item.preferredDate).split("-").reverse().join("-"), scheduledTime: item.scheduledTime ?? item.preferredTime, note: item.assignmentNote ?? "" }); } catch (reason) { handleError(reason); } };
  const submitAssignment = async (event: FormEvent) => { event.preventDefault(); if (!selected) return; setBusy(true); setError(""); setNotice(""); try { await assignAppointment(selected.appointment.referenceId, { ...form, scheduledDate: toDisplayDate(form.scheduledDate) }); setNotice(selected.appointment.assignedDoctor ? "Appointment reassigned successfully." : "Appointment assigned successfully."); setSelected(await getAppointmentDetail(selected.appointment.referenceId)); await load(); } catch (reason) { handleError(reason); } finally { setBusy(false); } };
  const closeAppointment = async (status: "COMPLETED" | "CANCELLED") => { if (!selected) return; const note = status === "CANCELLED" ? "Cancelled by admin." : window.prompt("Add a short note to mark this appointment completed:"); if (!note) return; setBusy(true); try { await changeAppointmentStatus(selected.appointment.referenceId, status, note); setNotice(`Appointment marked ${status.toLowerCase()}.`); setSelected(await getAppointmentDetail(selected.appointment.referenceId)); await load(); } catch (reason) { handleError(reason); } finally { setBusy(false); } };
  const logout = async () => { setLoggingOut(true); await logoutAdmin(); navigate("/login", { replace: true }); };
  return <div className="admin-appointments-shell"><AdminSidebar onLogout={() => void logout()} loggingOut={loggingOut} /><main className="admin-appointments-page"><header className="appointments-heading"><div><small>CARE COORDINATION</small><h1>Appointment Requests</h1><p>Review requests, assign a Doctor and follow every child’s care journey.</p></div><div className="appointments-admin"><span>👩‍💼</span><strong>Admin</strong></div></header>
    {error && <p className="appointments-alert appointments-alert--error" role="alert">{error}</p>}{notice && <p className="appointments-alert appointments-alert--success" role="status">{notice}</p>}
    <nav className="appointment-tabs" aria-label="Appointment status">{tabs.map(([value, key, label]) => <button className={active === value ? "is-active" : ""} onClick={() => { setActive(value); setSelected(null); }} type="button" key={value}>{label}<b>{summary[key]}</b></button>)}</nav>
    <div className="appointment-workspace"><section className="appointment-request-panel" aria-label="Appointment requests">{loading ? <div className="appointments-loading">Loading appointment requests…</div> : items.length === 0 ? <div className="appointments-empty"><span>🧸</span><h2>No appointments here</h2><p>New requests will appear automatically.</p></div> : <div className="appointment-request-list">{items.map((item) => <button className={`appointment-request${selected?.appointment.referenceId === item.referenceId ? " is-selected" : ""}`} type="button" onClick={() => void choose(item)} key={item.referenceId}><span className="appointment-request__avatar">🧒</span><span><strong>{item.childName}</strong><small>{item.childAge} · Parent: {item.parentName}</small><small>{item.preferredDate}, {item.preferredTime}</small></span><span><i className={`appointment-status appointment-status--${item.status.toLowerCase()}`}>{item.status === "REQUESTED" ? "PENDING" : item.status}</i><small>{item.assignedDoctor ? `Dr. ${item.assignedDoctor.firstName}` : "Select to assign"}</small></span></button>)}</div>}</section>
      <aside className="appointment-action-panel">{!selected ? <div className="appointments-empty"><span>🩺</span><h2>Select an appointment</h2><p>Patient details and assignment controls will appear here.</p></div> : <><header><div><small>{selected.appointment.referenceId}</small><h2>{selected.appointment.childName}</h2><p>{selected.appointment.childAge} · Patient ID {selected.appointment.patientId}</p></div><i className={`appointment-status appointment-status--${selected.appointment.status.toLowerCase()}`}>{selected.appointment.status}</i></header><div className="appointment-contact-grid"><p><span>Parent</span><b>{selected.appointment.parentName}</b></p><p><span>Phone</span><b>{selected.appointment.phone}</b></p><p><span>Email</span><b>{selected.appointment.email}</b></p><p><span>Requested</span><b>{selected.appointment.preferredDate} · {selected.appointment.preferredTime}</b></p></div>
        {(selected.appointment.status === "REQUESTED" || selected.appointment.status === "ASSIGNED") && <form className="assignment-form" onSubmit={submitAssignment}><h3>{selected.appointment.assignedDoctor ? "Reassign Patient" : "Assign Patient"}</h3><label>Select Doctor<select value={form.doctorId} onChange={(event) => setForm({ ...form, doctorId: event.target.value })} required><option value="">Choose an active Doctor</option>{doctors.map((doctor) => <option value={doctor.doctorId} key={doctor.doctorId}>Dr. {doctor.firstName} {doctor.lastName} — {doctor.designation}</option>)}</select></label><div><label>Appointment Date<input type="date" min={today} value={form.scheduledDate} onChange={(event) => setForm({ ...form, scheduledDate: event.target.value })} required /></label><label>Time<select value={form.scheduledTime} onChange={(event) => setForm({ ...form, scheduledTime: event.target.value })} required><option value="">Select time</option>{times.map((time) => <option key={time}>{time}</option>)}</select></label></div><label>Note (optional)<textarea maxLength={500} value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} placeholder="Add care or assignment instructions" /></label><button type="submit" disabled={busy}>{busy ? "Saving…" : selected.appointment.assignedDoctor ? "Reassign Doctor" : "Assign Doctor"}</button></form>}
        {selected.caseHistory && <section className="appointment-case-preview"><h3>Case History</h3><p><b>Visit #{String(selected.caseHistory.appointmentNumber)}</b> · {String(selected.caseHistory.appointmentDate)}</p><p>{String(selected.caseHistory.caseHistory)}</p></section>}
        {selected.logs.length > 0 && <details className="appointment-timeline"><summary>Activity history ({selected.logs.length})</summary>{selected.logs.map((log) => <p key={String(log.id)}><b>{String(log.event).replaceAll("_", " ")}</b><span>{new Date(String(log.createdAt)).toLocaleString()}</span>{log.note && <small>{String(log.note)}</small>}</p>)}</details>}
        {selected.appointment.status === "ASSIGNED" && <div className="appointment-close-actions"><button type="button" onClick={() => void closeAppointment("COMPLETED")} disabled={busy}>Mark Completed</button><button type="button" onClick={() => void closeAppointment("CANCELLED")} disabled={busy}>Cancel Appointment</button></div>}
      </>}</aside></div></main></div>;
};
